#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT1/capacity)
state=$(cat /sys/class/power_supply/BAT1/status)

charge=""
if [[ $state != "Discharging" ]]; then
	charge="󱐋"
fi

# Older way
#
# if [[ $capacity -gt 80 ]]; then
#	 echo "󰂁 $capacity%$charge"
# elif [[ $capacity -gt 60 ]]; then
#	 echo "󰁿 $capacity%$charge"
# elif [[ $capacity -gt 40 ]]; then
#	 echo "󰁽 $capacity%$charge"
# elif [[ $capacity -gt 20 ]]; then
#	 echo "󰁻 $capacity%$charge"
# else
#	 echo "󰂎 $capacity%$charge"
# fi

# One more way to do the same thing
level=$((capacity / 20))

case $level in
	0)
		echo "󰂎 $capacity%$charge"
		;;
	1)
		echo "󰁻 $capacity%$charge"
		;;
	2)
		echo "󰁽 $capacity%$charge"
		;;
	3)
		echo "󰁿 $capacity%$charge"
		;;
	*)
		echo "󰂁 $capacity%$charge"
		;;
esac
