#!/bin/sh

rx1=$(cat /sys/class/net/wlp9s0/statistics/rx_bytes)
tx1=$(cat /sys/class/net/wlp9s0/statistics/tx_bytes)
while sleep 1s; do
#	rx2=$(cat /sys/class/net/wlp9s0/statistics/rx_bytes)
#	tx2=$(cat /sys/class/net/wlp9s0/statistics/tx_bytes)
#	# echo Download rate: "$((rx2-rx1))" B/s, Upload rate: "$((tx2-tx1))" B/s
#	echo 󰁅 "$((rx2-rx1))" B/s, 󰁝 "$((tx2-tx1))" B/s
#	rx1=$rx2
#	tx1=$tx2

	rx2=$(cat /sys/class/net/wlp9s0/statistics/rx_bytes)
	tx2=$(cat /sys/class/net/wlp9s0/statistics/tx_bytes)
	network_info="󰁅 $((rx2-rx1)) B/s, 󰁝 $((tx2-tx1)) B/s"
	echo $network_info
	rx1=$rx2
	tx1=$tx2

done
