#!/bin/sh

rx1=$(cat /sys/class/net/wlp9s0/statistics/rx_bytes)
tx1=$(cat /sys/class/net/wlp9s0/statistics/tx_bytes)

sleep 1s

rx2=$(cat /sys/class/net/wlp9s0/statistics/rx_bytes)
tx2=$(cat /sys/class/net/wlp9s0/statistics/tx_bytes)

# echo Down: "$((rx2-rx1))" B/s, Up: "$((tx2-tx1))" B/s
echo 󰁅 "$((rx2-rx1))" B/s, 󰁝 "$((tx2-tx1))" B/s
