#!/bin/sh

option=$(echo -e "hibernate\nsuspend\npoweroff\nreboot\n" | dmenu -i -p "Select an option: ")

if [ "$option" != "" ]
then
	echo "Power option selected: $option"
	echo "Asking for confirmation..."
	if [ $(echo -e "No\nYes" | dmenu -i -p "Are you sure? ") = "Yes" ]
	then
		systemctl $option
	else
		echo "Operation aborted"
	fi
else
	echo "No option selected..."
fi
