#!/bin/sh

option=$(echo -e "suspend\nhibernate\npoweroff\nreboot\n" | dmenu -i -p "Select an option: ")

if [ "$option" != "" ]
then
	echo "Power option selected: $option"
	systemctl $option
	if [ "$option" == "suspend" ]
	then
		slock
	fi
# Optional: Asking for confirmation
#
# echo "Asking for confirmation..."
# if [ $(echo -e "no\nyes" | dmenu -i -p "Are you sure? ") = "yes" ]
# then
# 	systemctl $option
# 	if [ "$option" == "suspend" ]
# 	then
# 		slock
# 	fi
# else
# 	echo "Operation aborted"
# fi
else
	echo "No option selected..."
fi
